---
build_from:
  aarch64: ghcr.io/hassio-addons/base:16.3.4
  amd64: ghcr.io/hassio-addons/base:16.3.4
  armhf: ghcr.io/hassio-addons/base:16.3.4
  armv7: ghcr.io/hassio-addons/base:16.3.4
  i386: ghcr.io/hassio-addons/base:16.3.4
