---
build_from:
  aarch64: ghcr.io/hassio-addons/base:15.0.5
  amd64: ghcr.io/hassio-addons/base:15.0.5
  armhf: ghcr.io/hassio-addons/base:15.0.5
  armv7: ghcr.io/hassio-addons/base:15.0.5
  i386: ghcr.io/hassio-addons/base:15.0.5
