---
build_from:
  aarch64: ghcr.io/hassio-addons/base:16.3.6
  amd64: ghcr.io/hassio-addons/base:16.3.6
  armhf: ghcr.io/hassio-addons/base:16.3.6
  armv7: ghcr.io/hassio-addons/base:16.3.6
  i386: ghcr.io/hassio-addons/base:16.3.6
