---
build_from:
  aarch64: ghcr.io/hassio-addons/base:16.1.2
  amd64: ghcr.io/hassio-addons/base:16.1.2
  armhf: ghcr.io/hassio-addons/base:16.1.2
  armv7: ghcr.io/hassio-addons/base:16.1.2
  i386: ghcr.io/hassio-addons/base:16.1.2
