---
build_from:
  aarch64: ghcr.io/hassio-addons/base:16.3.3
  amd64: ghcr.io/hassio-addons/base:16.3.3
  armhf: ghcr.io/hassio-addons/base:16.3.3
  armv7: ghcr.io/hassio-addons/base:16.3.3
  i386: ghcr.io/hassio-addons/base:16.3.3
